### ISSUE TITLE
License

### ISSUE THREAD

**Issue by 12people** [Epikly/Argon-Design-System-Sketch#1]
I'm thinking of creating a free and open-source wireframe kit (I'd like to use the CC BY-SA license) and I'd love to be able to use your Sketch file as a start for it.

The Readme here says that the project is free and open-source; however, no license is mentioned. Could you please add a license so that I know whether I can my wireframe kit on top of the Argon sketch file?

**Comment by michelve** [comment]
yes u can - just credit us back
